package com.sitech.cntt.inter;

import com.sitech.cntt.metadata.domain.FortressTest;
import com.sitech.cntt.metadata.domain.FortressTestExample;
import java.util.List;
import java.util.Map;

public interface FortressTestMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FORTRESS_TEST
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String accept);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FORTRESS_TEST
	 * @mbggenerated
	 */
	int insert(FortressTest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FORTRESS_TEST
	 * @mbggenerated
	 */
	int insertSelective(FortressTest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FORTRESS_TEST
	 * @mbggenerated
	 */
	List<FortressTest> selectByExample(FortressTestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FORTRESS_TEST
	 * @mbggenerated
	 */
	FortressTest selectByPrimaryKey(String accept);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FORTRESS_TEST
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(FortressTest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FORTRESS_TEST
	 * @mbggenerated
	 */
	int updateByPrimaryKey(FortressTest record);

	List<FortressTest> qryDataByMap(Map inMap);

    int updateFortressStatus(FortressTest record);

	int updateRemark(String remark);
}