package com.sitech.cntt.inter;

import com.sitech.cntt.metadata.domain.IaServconfigDict;
import com.sitech.cntt.metadata.domain.IaServconfigDictExample;
import java.util.List;

public interface IaServconfigDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IA_SERVCONFIG_DICT
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long servId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IA_SERVCONFIG_DICT
     *
     * @mbggenerated
     */
    int insert(IaServconfigDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IA_SERVCONFIG_DICT
     *
     * @mbggenerated
     */
    int insertSelective(IaServconfigDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IA_SERVCONFIG_DICT
     *
     * @mbggenerated
     */
    List<IaServconfigDict> selectByExample(IaServconfigDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IA_SERVCONFIG_DICT
     *
     * @mbggenerated
     */
    IaServconfigDict selectByPrimaryKey(Long servId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IA_SERVCONFIG_DICT
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IaServconfigDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IA_SERVCONFIG_DICT
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IaServconfigDict record);

	List<IaServconfigDict> selectAll();
}