package com.sitech.cntt.metadata.domain;

import java.io.Serializable;
import java.util.Date;

import com.alibaba.fastjson.annotation.JSONField;
import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel("交互信息实体")
public class ConRel implements Serializable{
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONREL.OP_CODE
     *
     * @mbggenerated
     */
	@ApiModelProperty(value = "操作代码")
	@JSONField(name = "OP_CODE")
	@JsonProperty("OP_CODE")
    private int opCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONREL.OP_NAME
     *
     * @mbggenerated
     */
	@ApiModelProperty(value = "操作名")
	@JSONField(name = "OP_NAME")
	@JsonProperty("OP_NAME")
    private String opName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONREL.OP_TIME
     *
     * @mbggenerated
     */
	@ApiModelProperty(value = "操作时间")
	@JSONField(name = "OP_TIME")
	@JsonProperty("OP_TIME")
    private Date opTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONREL.ID_NO
     *
     * @mbggenerated
     */
	@ApiModelProperty(value = "主产品实例ID")
	@JSONField(name = "ID_NO")
	@JsonProperty("ID_NO")
    private String idNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONREL.PRICE
     *
     * @mbggenerated
     */
	@ApiModelProperty(value = "价格")
	@JSONField(name = "PRICE")
	@JsonProperty("PRICE")
    private double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONREL.LOGIN_NO
     *
     * @mbggenerated
     */
	@ApiModelProperty(value = "工号")
	@JSONField(name = "LOGIN_NO")
	@JsonProperty("LOGIN_NO")
    private String loginNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONREL.LOGIN_ACCEPT
     *
     * @mbggenerated
     */
	@ApiModelProperty(value = "注册许可")
	@JSONField(name = "LOGIN_ACCEPT")
	@JsonProperty("LOGIN_ACCEPT")
    private String loginAccept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONREL.ASSURE_CUST_ID
     *
     * @mbggenerated
     */
	@ApiModelProperty(value = "担保人客户标识")
	@JSONField(name = "ASSURE_CUST_ID")
	@JsonProperty("ASSURE_CUST_ID")
    private String assureCustId;
	
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONREL.OP_NOTE
     *
     * @mbggenerated
     */
	@ApiModelProperty(value = "操作记录")
	@JSONField(name = "OP_NOTE")
	@JsonProperty("OP_NOTE")
    private String opNote;
	
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONREL.BILL_ID
     *
     * @mbggenerated
     */
	@ApiModelProperty(value = "票号 发票或者免填单号")
	@JSONField(name = "BILL_ID")
	@JsonProperty("BILL_ID")
    private String billId;
	
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONREL.PHONE_NO
     *
     * @mbggenerated
     */
	@ApiModelProperty(value = "在客服中相当于受理号码")
	@JSONField(name = "PHONE_NO")
	@JsonProperty("PHONE_NO")
    private String phoneNo;
	
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONREL.SUB_ORDER_ID
     *
     * @mbggenerated
     */
	@ApiModelProperty(value = "子订单号")
	@JSONField(name = "SUB_ORDER_ID")
	@JsonProperty("SUB_ORDER_ID")
    private String subOrderId;
	
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONREL.TOTAL_FEE
     *
     * @mbggenerated
     */
	@ApiModelProperty(value = "费用金额")
	@JSONField(name = "TOTAL_FEE")
	@JsonProperty("TOTAL_FEE")
    private double totalFee;
	
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONREL.CHNN_NAME
     *
     * @mbggenerated
     */
	@ApiModelProperty(value = "渠道名")
	@JSONField(name = "CHNN_NAME")
	@JsonProperty("CHNN_NAME")
    private String chnn;
	
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONREL.OP_CODE
     *
     * @return the value of CONREL.OP_CODE
     *
     * @mbggenerated
     */
    public int getOpCode() {
        return opCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONREL.OP_CODE
     *
     * @param servId the value for CONREL.OP_CODE
     *
     * @mbggenerated
     */
    public void setOpCode(int opCode) {
        this.opCode = opCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONREL.OP_NAME
     *
     * @return the value of ICONREL.OP_NAME
     *
     * @mbggenerated
     */
    public String getOpName() {
        return opName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONREL.OP_NAME
     *
     * @param appCode the value for CONREL.OP_CODENAME
     * @mbggenerated
     */
    public void setOpName(String opName) {
        this.opName=opName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONREL.OP_TIME
     *
     * @return the value of CONREL.OP_TIME
     *
     * @mbggenerated
     */
    public Date getOpTime() {
        return opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONREL.OP_TIME
     *
     * @param servCode the value for CONREL.OP_TIME
     *
     * @mbggenerated
     */
    public void setOpTime(Date opTime) {
        this.opTime=opTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONREL.ID_NO
     *
     * @return the value of CONREL.ID_NO
     *
     * @mbggenerated
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONREL.ID_NO
     *
     * @param servName the value for CONREL.ID_NO
     *
     * @mbggenerated
     */
    public void setIdNo(String idNo) {
    	this.idNo=idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONREL.PRICE
     *
     * @return the value of CONREL.PRICE
     *
     * @mbggenerated
     */
    public double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONREL.PRICE
     *
     * @param servType the value for CONREL.PRICE
     *
     * @mbggenerated
     */
    public void setPrice(double price) {
        this.price=price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONREL.LOGIN_NO
     *
     * @return the value of CONREL.LOGIN_NO
     *
     * @mbggenerated
     */
    public String getLoginNo() {
        return loginNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONREL.LOGIN_NO
     *
     * @param chnCodes the value for CONREL.LOGIN_NO
     *
     * @mbggenerated
     */
    public void setLoginNo(String loginNo) {
        this.loginNo=loginNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONREL.LOGIN_ACCEPT
     *
     * @return the value of CONREL.LOGIN_ACCEPT
     *
     * @mbggenerated
     */
    public String getLoginAccept() {
        return loginAccept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONREL.LOGIN_ACCEPT
     *
     * @param funcCodes the value for CONREL.LOGIN_ACCEPT
     *
     * @mbggenerated
     */
    public void setLoginAccept(String loginAccept) {
        this.loginAccept=loginAccept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONREL.ASSURE_CUST_ID
     *
     * @return the value of CONREL.ASSURE_CUST_ID
     *
     * @mbggenerated
     */
    public String getAssureCustId() {
        return assureCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONREL.ASSURE_CUST_ID
     *
     * @param servPath the value for CONREL.ASSURE_CUST_ID
     *
     * @mbggenerated
     */
    public void setAssureCustId(String assureCustId) {
    	this.assureCustId=assureCustId;
    }

    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONREL.OP_NOTE
     *
     * @return the value of CONREL.OP_NOTE
     *
     * @mbggenerated
     */
	public String getOpNote() {
		return opNote;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONREL.OP_NOTE
     *
     * @param servPath the value for CONREL.OP_NOTE
     *
     * @mbggenerated
     */
	public void setOpNote(String opNote) {
		this.opNote = opNote;
	}

	
	 /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONREL.BILL_ID
     *
     * @return the value of CONREL.BILL_ID
     *
     * @mbggenerated
     */
	public String getBillId() {
		return billId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONREL.BILL_ID
     *
     * @param servPath the value for CONREL.BILL_ID
     *
     * @mbggenerated
     */
	public void setBillId(String billId) {
		this.billId = billId;
	}

	 /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONREL.PHONE_NO
     *
     * @return the value of CONREL.PHONE_NO
     *
     * @mbggenerated
     */
	public String getPhoneNo() {
		return phoneNo;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONREL.PHONE_NO
     *
     * @param servPath the value for CONREL.PHONE_NO
     *
     * @mbggenerated
     */
	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

	 /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONREL.SUB_ORDER_ID
     *
     * @return the value of CONREL.SUB_ORDER_ID
     *
     * @mbggenerated
     */
	public String getSubOrderId() {
		return subOrderId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONREL.SUB_ORDER_ID
     *
     * @param servPath the value for CONREL.SUB_ORDER_ID
     *
     * @mbggenerated
     */
	public void setSubOrderId(String subOrderId) {
		this.subOrderId = subOrderId;
	}

	 /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONREL.TOTAL_FEE
     *
     * @return the value of CONREL.BILL_ID
     *
     * @mbggenerated
     */
	public double getTotalFee() {
		return totalFee;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONREL.TOTAL_FEE
     *
     * @param servPath the value for CONREL.ASSURE_CUST_ID
     *
     * @mbggenerated
     */
	public void setTotalFee(double totalFee) {
		this.totalFee = totalFee;
	}

	 /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONREL.CHNN_NAME
     *
     * @return the value of CONREL.CHNN_NAME
     *
     * @mbggenerated
     */
	public String getChnn() {
		return chnn;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONREL.CHNN_NAME
     *
     * @param servPath the value for CONREL.CHNN_NAME
     *
     * @mbggenerated
     */
	public void setChnn(String chnn) {
		this.chnn = chnn;
	}
    
}
