package com.sitech.cntt.metadata.domain;

import java.io.Serializable;

import com.alibaba.fastjson.annotation.JSONField;
import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value = "服务配置实体")
public class IaServconfigDict implements Serializable{

	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IA_SERVCONFIG_DICT.SERV_ID
     *
     * @mbggenerated
     */
	@ApiModelProperty(value = "服务标识")
	@JSONField(name = "SERV_ID")
	@JsonProperty("SERV_ID")
    private Long servId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IA_SERVCONFIG_DICT.APP_CODE
     *
     * @mbggenerated
     */
	@ApiModelProperty(value = "应用编码")
	@JSONField(name = "APP_CODE")
	@JsonProperty("APP_CODE")
    private String appCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IA_SERVCONFIG_DICT.SERV_CODE
     *
     * @mbggenerated
     */
	@ApiModelProperty(value = "服务编码")
	@JSONField(name = "SERV_CODE")
	@JsonProperty("SERV_CODE")
    private String servCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IA_SERVCONFIG_DICT.SERV_NAME
     *
     * @mbggenerated
     */
	@ApiModelProperty(value = "服务名称")
	@JSONField(name = "SERV_NAME")
	@JsonProperty("SERV_NAME")
    private String servName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IA_SERVCONFIG_DICT.SERV_TYPE
     *
     * @mbggenerated
     */
	@ApiModelProperty(value = "服务类型")
	@JSONField(name = "	SERV_TYPE")
	@JsonProperty("	SERV_TYPE")
    private String servType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IA_SERVCONFIG_DICT.CHN_CODES
     *
     * @mbggenerated
     */
	@ApiModelProperty(value = "渠道编码")
	@JSONField(name = "CHN_CODES")
	@JsonProperty("CHN_CODES")
    private String chnCodes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IA_SERVCONFIG_DICT.FUNC_CODES
     *
     * @mbggenerated
     */
	@ApiModelProperty(value = "功能编码")
	@JSONField(name = "FUNC_CODES")
	@JsonProperty("FUNC_CODES")
    private String funcCodes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IA_SERVCONFIG_DICT.SERV_PATH
     *
     * @mbggenerated
     */
	@ApiModelProperty(value = "方法路径")
	@JSONField(name = "SERV_PATH")
	@JsonProperty("SERV_PATH")
    private String servPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IA_SERVCONFIG_DICT.SERV_ID
     *
     * @return the value of IA_SERVCONFIG_DICT.SERV_ID
     *
     * @mbggenerated
     */
    public Long getServId() {
        return servId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IA_SERVCONFIG_DICT.SERV_ID
     *
     * @param servId the value for IA_SERVCONFIG_DICT.SERV_ID
     *
     * @mbggenerated
     */
    public void setServId(Long servId) {
        this.servId = servId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IA_SERVCONFIG_DICT.APP_CODE
     *
     * @return the value of IA_SERVCONFIG_DICT.APP_CODE
     *
     * @mbggenerated
     */
    public String getAppCode() {
        return appCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IA_SERVCONFIG_DICT.APP_CODE
     *
     * @param appCode the value for IA_SERVCONFIG_DICT.APP_CODE
     *
     * @mbggenerated
     */
    public void setAppCode(String appCode) {
        this.appCode = appCode == null ? null : appCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IA_SERVCONFIG_DICT.SERV_CODE
     *
     * @return the value of IA_SERVCONFIG_DICT.SERV_CODE
     *
     * @mbggenerated
     */
    public String getServCode() {
        return servCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IA_SERVCONFIG_DICT.SERV_CODE
     *
     * @param servCode the value for IA_SERVCONFIG_DICT.SERV_CODE
     *
     * @mbggenerated
     */
    public void setServCode(String servCode) {
        this.servCode = servCode == null ? null : servCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IA_SERVCONFIG_DICT.SERV_NAME
     *
     * @return the value of IA_SERVCONFIG_DICT.SERV_NAME
     *
     * @mbggenerated
     */
    public String getServName() {
        return servName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IA_SERVCONFIG_DICT.SERV_NAME
     *
     * @param servName the value for IA_SERVCONFIG_DICT.SERV_NAME
     *
     * @mbggenerated
     */
    public void setServName(String servName) {
        this.servName = servName == null ? null : servName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IA_SERVCONFIG_DICT.SERV_TYPE
     *
     * @return the value of IA_SERVCONFIG_DICT.SERV_TYPE
     *
     * @mbggenerated
     */
    public String getServType() {
        return servType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IA_SERVCONFIG_DICT.SERV_TYPE
     *
     * @param servType the value for IA_SERVCONFIG_DICT.SERV_TYPE
     *
     * @mbggenerated
     */
    public void setServType(String servType) {
        this.servType = servType == null ? null : servType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IA_SERVCONFIG_DICT.CHN_CODES
     *
     * @return the value of IA_SERVCONFIG_DICT.CHN_CODES
     *
     * @mbggenerated
     */
    public String getChnCodes() {
        return chnCodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IA_SERVCONFIG_DICT.CHN_CODES
     *
     * @param chnCodes the value for IA_SERVCONFIG_DICT.CHN_CODES
     *
     * @mbggenerated
     */
    public void setChnCodes(String chnCodes) {
        this.chnCodes = chnCodes == null ? null : chnCodes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IA_SERVCONFIG_DICT.FUNC_CODES
     *
     * @return the value of IA_SERVCONFIG_DICT.FUNC_CODES
     *
     * @mbggenerated
     */
    public String getFuncCodes() {
        return funcCodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IA_SERVCONFIG_DICT.FUNC_CODES
     *
     * @param funcCodes the value for IA_SERVCONFIG_DICT.FUNC_CODES
     *
     * @mbggenerated
     */
    public void setFuncCodes(String funcCodes) {
        this.funcCodes = funcCodes == null ? null : funcCodes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IA_SERVCONFIG_DICT.SERV_PATH
     *
     * @return the value of IA_SERVCONFIG_DICT.SERV_PATH
     *
     * @mbggenerated
     */
    public String getServPath() {
        return servPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IA_SERVCONFIG_DICT.SERV_PATH
     *
     * @param servPath the value for IA_SERVCONFIG_DICT.SERV_PATH
     *
     * @mbggenerated
     */
    public void setServPath(String servPath) {
        this.servPath = servPath == null ? null : servPath.trim();
    }
}