package com.sitech.cntt.metadata.domain;

import java.util.Date;

public class FortressTest {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FORTRESS_TEST.ACCEPT
	 * @mbggenerated
	 */
	private String accept;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FORTRESS_TEST.REMARK
	 * @mbggenerated
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FORTRESS_TEST.DSP_STATUS
	 * @mbggenerated
	 */
	private String dspStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FORTRESS_TEST.DSP_ACCEPT
	 * @mbggenerated
	 */
	private String dspAccept;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FORTRESS_TEST.DSP_POSITION
	 * @mbggenerated
	 */
	private String dspPosition;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FORTRESS_TEST.DSP_UPDATE_TIME
	 * @mbggenerated
	 */
	private Date dspUpdateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FORTRESS_TEST.STATUS_CD
	 * @mbggenerated
	 */
	private String statusCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FORTRESS_TEST.STATUS_DATE
	 * @mbggenerated
	 */
	private Date statusDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FORTRESS_TEST.ACCEPT
	 * @return  the value of FORTRESS_TEST.ACCEPT
	 * @mbggenerated
	 */
	public String getAccept() {
		return accept;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FORTRESS_TEST.ACCEPT
	 * @param accept  the value for FORTRESS_TEST.ACCEPT
	 * @mbggenerated
	 */
	public void setAccept(String accept) {
		this.accept = accept == null ? null : accept.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FORTRESS_TEST.REMARK
	 * @return  the value of FORTRESS_TEST.REMARK
	 * @mbggenerated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FORTRESS_TEST.REMARK
	 * @param remark  the value for FORTRESS_TEST.REMARK
	 * @mbggenerated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FORTRESS_TEST.DSP_STATUS
	 * @return  the value of FORTRESS_TEST.DSP_STATUS
	 * @mbggenerated
	 */
	public String getDspStatus() {
		return dspStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FORTRESS_TEST.DSP_STATUS
	 * @param dspStatus  the value for FORTRESS_TEST.DSP_STATUS
	 * @mbggenerated
	 */
	public void setDspStatus(String dspStatus) {
		this.dspStatus = dspStatus == null ? null : dspStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FORTRESS_TEST.DSP_ACCEPT
	 * @return  the value of FORTRESS_TEST.DSP_ACCEPT
	 * @mbggenerated
	 */
	public String getDspAccept() {
		return dspAccept;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FORTRESS_TEST.DSP_ACCEPT
	 * @param dspAccept  the value for FORTRESS_TEST.DSP_ACCEPT
	 * @mbggenerated
	 */
	public void setDspAccept(String dspAccept) {
		this.dspAccept = dspAccept == null ? null : dspAccept.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FORTRESS_TEST.DSP_POSITION
	 * @return  the value of FORTRESS_TEST.DSP_POSITION
	 * @mbggenerated
	 */
	public String getDspPosition() {
		return dspPosition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FORTRESS_TEST.DSP_POSITION
	 * @param dspPosition  the value for FORTRESS_TEST.DSP_POSITION
	 * @mbggenerated
	 */
	public void setDspPosition(String dspPosition) {
		this.dspPosition = dspPosition == null ? null : dspPosition.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FORTRESS_TEST.DSP_UPDATE_TIME
	 * @return  the value of FORTRESS_TEST.DSP_UPDATE_TIME
	 * @mbggenerated
	 */
	public Date getDspUpdateTime() {
		return dspUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FORTRESS_TEST.DSP_UPDATE_TIME
	 * @param dspUpdateTime  the value for FORTRESS_TEST.DSP_UPDATE_TIME
	 * @mbggenerated
	 */
	public void setDspUpdateTime(Date dspUpdateTime) {
		this.dspUpdateTime = dspUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FORTRESS_TEST.STATUS_CD
	 * @return  the value of FORTRESS_TEST.STATUS_CD
	 * @mbggenerated
	 */
	public String getStatusCd() {
		return statusCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FORTRESS_TEST.STATUS_CD
	 * @param statusCd  the value for FORTRESS_TEST.STATUS_CD
	 * @mbggenerated
	 */
	public void setStatusCd(String statusCd) {
		this.statusCd = statusCd == null ? null : statusCd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FORTRESS_TEST.STATUS_DATE
	 * @return  the value of FORTRESS_TEST.STATUS_DATE
	 * @mbggenerated
	 */
	public Date getStatusDate() {
		return statusDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FORTRESS_TEST.STATUS_DATE
	 * @param statusDate  the value for FORTRESS_TEST.STATUS_DATE
	 * @mbggenerated
	 */
	public void setStatusDate(Date statusDate) {
		this.statusDate = statusDate;
	}
}